### ISSUE TITLE
redirect doesn't work in chrome

### ISSUE THREAD

**Issue by smartls** [ThunderDev1/reactjs-ts-identityserver#2]
it's strange, when I use internet explorer, the demo works fine, when open in chrome, redirect to spa doesn't work, and indentity server has no user claims.

**Comment by ThunderDev1** [comment]
Hi, thanks for your feedback. What version of chrome are you using ?

**Comment by smartls** [comment]
Hi, the version is 69.0.3497.81 32bits.

**Comment by ThunderDev1** [comment]
I'm able to run the project with the same version of chrome with no issues.
I've upgraded the project to dotnet core 2.1, this will unlikely solve your problem but you can give it a try ;)

**Comment by vcardins** [comment]
@smartls It's happening to me as well, after successfully logging in, it's not redirecting to the SPA. Could you share how you solved the issue?
PS: I'm using chrome as well

**Comment by wernerplumot** [comment]
Oops, it has been a while but it is working. As I can remember it was a
typo, some mistaken name.
You should really check the examples on Identityserver, it will solve your
problem.

FYI: I refactored all my code to Angular... why: just like that

Op di 16 jul. 2019 om 23:51 schreef Victor Cardins <notifications@github.com
