### ISSUE TITLE
response_type as code

### ISSUE THREAD

**Issue by kamalraturi** [ThunderDev1/reactjs-ts-identityserver#20]
@ThunderDev1 , I tried response_type as code (not implicit) in my SPA, for which I set the userManager.ts as ->  response_type: "code".

On identity server   AllowedGrantTypes = GrantTypes.Code, is set.

Just above settings I did but its not working. Always showing isConnected =false. So always login button appears (No logout).

**Comment by ThunderDev1** [comment]
Hi @kamalraturi I'm not quite sure what you are trying to achieve. Could you explain your use case? I don't this [authorization code flow](https://auth0.com/docs/flows/concepts/auth-code) is what you need, as this should only be used with a sever side app.
