### ISSUE TITLE
Does the Spa needs to be a full ASP.NET Core app?

### ISSUE THREAD

**Issue by eparizzi** [ThunderDev1/reactjs-ts-identityserver#5]
Hi, I'm starting to get around this whole IdentityServer stuff. I like your boilerplate since it's pretty similar to what we have to do.

So, you used the ASP.NET Core React/Redux SPA template for the client. But since the API is in a different project, I guess the client could just be a full create-react-app right? No server is actually needed for it to work with IdentityServer since all the auth stuff is handled by the client-side OIDC library, right?

Or is there any other benefit or requirement for the client to be a full ASP.NET Core app that I'm missing?

**Comment by ThunderDev1** [comment]
Hi, thanks for your feedback. Good question, this will depend on how you intend to deploy your app. Although it doesn't do much, the server part in the SPA does have a purpose. It enables you to serve static files, and manages the default route. If you're using Azure's App Service, this will be needed for it to work. However there are other solutions for hosting static SPA's such as Azure functions and more recently Azure Storage (preview) which seems to be the best way to go. More on this [here](https://medium.com/@philippbauknecht/best-way-to-host-a-single-page-application-spa-in-microsoft-azure-3e70cbd075c3)

**Comment by ThunderDev1** [comment]
The server part in the SPA project has now been removed ;)
