### ISSUE TITLE
SPA not running in IE or Edge

### ISSUE THREAD

**Issue by bencameron00** [ThunderDev1/reactjs-ts-identityserver#8]
Hi

Great project, love it.

IT doesn't seem to load in IE though. I'm getting the below content. Other sites work so JS isn't disabled.

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="react-ts-starter" content="yes">
  <title>react-ts-starter</title>
</head>

<body>
  <noscript>If you're seeing this message, that means
    <strong>JavaScript has been disabled on your browser</strong>, please
    <strong>enable JS</strong> to make this app work.
  </noscript>

  <div id="root"></div>
<script type="text/javascript" src="main.js"></script></body>
</html>

**Comment by bencameron00** [comment]
I think this could be something to do with the ts -> js setup. Is this something you will be able to help with?

**Comment by bencameron00** [comment]
@ThunderDev1

**Comment by bencameron00** [comment]
I think I have found the issue. Its to do with the GitHubButton component that is rendered on the Nav component. If that is removed the rest of the app works as expected.

**Comment by ThunderDev1** [comment]
Thanks for pointing that out 😄
I have removed the button for the time being.

**Comment by bencameron00** [comment]
No problem! Its a great package. Thank you for putting it together.
One other question, what the Manage controller for and how do you access it?

**Comment by ThunderDev1** [comment]
The Manage controller is for managing your user account (update password, username...) not sure if it's used at the moment.
